/*
 * File: app/view/HelpPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sxapim.view.HelpPanel', {
    extend: 'Ext.panel.Panel',

    html: '',
    itemId: 'helpPanel',
    layout: {
        hideCollapseTool: false,
        animate: true,
        sequence: true,
        type: 'accordion'
    },
    bodyBorder: false,
    closable: true,
    glyph: '63@Sosa',
    title: 'Help Center',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            defaults: {
                bodyPadding: '0 10'
            },
            items: [
                {
                    xtype: 'panel',
                    html: '<p>This application is a backend to manage and monitor API exposed and processed by an SXAPI plateform. For more information about this project, see sxapi on gthub</p>',
                    title: 'Introduction'
                },
                {
                    xtype: 'panel',
                    html: '<p>This application is a backend to manage and monitor API exposed and processed by an SXAPI plateform. For more information about this project, see sxapi on gthub</p>',
                    title: 'User management'
                },
                {
                    xtype: 'panel',
                    title: 'Report a bug'
                }
            ]
        });

        me.callParent(arguments);
    }

});