/*
 * File: app/view/HomePanel.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sxapim.view.HomePanel', {
    extend: 'Ext.panel.Panel',

    html: '<h2>Welcome to SXAPI Manager</h2><p>This application is a backend to manage and monitor API exposed and processed by an SXAPI plateform. For more information about this project, see sxapi on gthub</p>',
    itemId: 'homePanel',
    bodyBorder: false,
    bodyPadding: 10,
    closable: true,
    title: 'Home',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});