/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sxapim.view.MainView', {
    extend: 'Ext.container.Viewport',

    itemId: 'mainView',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    region: 'north',
                    height: 50,
                    html: '<h1>SXAPIM</h1>',
                    itemId: 'topPanel',
                    layout: {
                        align: 'center',
                        pack: 'center',
                        type: 'vbox'
                    }
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'west',
                    split: true,
                    frame: true,
                    itemId: 'menuPanel',
                    width: 150,
                    collapseDirection: 'left',
                    collapsed: false,
                    collapsible: true,
                    title: 'Menu',
                    items: [
                        {
                            xtype: 'menu',
                            floating: false,
                            items: [
                                {
                                    xtype: 'menuitem',
                                    itemId: 'home',
                                    text: 'Home'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'about',
                                    text: 'About Us'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'contact',
                                    text: 'Contact us'
                                }
                            ],
                            listeners: {
                                click: {
                                    fn: me.onMenuClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    flex: 3,
                    region: 'center',
                    itemId: 'contentPanel',
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'homePanel',
                            layout: {
                                align: 'center',
                                pack: 'center',
                                type: 'vbox'
                            },
                            title: 'Home',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Home View'
                                }
                            ],
                            tabConfig: {
                                xtype: 'tab',
                                flex: 1
                            }
                        },
                        {
                            xtype: 'panel',
                            itemId: 'aboutPanel',
                            layout: {
                                align: 'center',
                                pack: 'center',
                                type: 'vbox'
                            },
                            title: 'About Us',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'About Us View'
                                }
                            ],
                            tabConfig: {
                                xtype: 'tab',
                                flex: 1
                            }
                        },
                        {
                            xtype: 'panel',
                            itemId: 'contactPanel',
                            layout: {
                                align: 'center',
                                pack: 'center',
                                type: 'vbox'
                            },
                            title: 'Contact Us',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Contact Us View'
                                }
                            ],
                            tabConfig: {
                                xtype: 'tab',
                                flex: 1
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onMenuClick: function(menu, item, e, eOpts) {
        location.hash = item.itemId;
    }

});