/*
 * File: app/view/UsersPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sxapim.view.UsersPanel', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar'
    ],

    itemId: 'usersPanel',
    layout: {
        type: 'border'
    },
    closable: true,
    glyph: '225@Sosa',
    title: 'User\'s list',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 3,
                    region: 'center',
                    id: '',
                    itemId: 'usersgrid',
                    store: 'UsersStore',
                    viewConfig: {
                        itemId: 'UserGridView'
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            defaultWidth: 50,
                            dataIndex: 'id',
                            text: 'Id'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'firstname',
                            text: 'Firstname'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'lastname',
                            text: 'Lastname',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'mail',
                            text: 'Mail'
                        },
                        {
                            xtype: 'gridcolumn',
                            defaultWidth: 50,
                            dataIndex: 'pin',
                            text: 'Pin'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'east',
                    itemId: 'usersgraph',
                    width: 300,
                    closable: true,
                    collapsible: true,
                    glyph: '70@Sosa',
                    title: 'Graphic',
                    titleCollapse: true,
                    dockedItems: [
                        {
                            xtype: 'chart',
                            dock: 'right',
                            width: 300,
                            autoSize: true,
                            animate: true,
                            store: 'UsersStore',
                            theme: 'Blue',
                            axes: [
                                {
                                    type: 'Category',
                                    fields: [
                                        'firstname'
                                    ],
                                    position: 'right'
                                },
                                {
                                    type: 'Numeric',
                                    fields: [
                                        'visitcounter'
                                    ],
                                    position: 'top',
                                    decimals: 0,
                                    minimum: 0
                                }
                            ],
                            series: [
                                {
                                    type: 'bar',
                                    label: {
                                        display: 'insideEnd',
                                        field: 'visitcounter',
                                        color: '#fff',
                                        'text-anchor': 'middle'
                                    },
                                    xField: 'firstname',
                                    yField: 'visitcounter',
                                    stacked: false
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 2,
                    region: 'south',
                    split: true,
                    itemId: 'userDetail',
                    layout: {
                        type: 'fit'
                    },
                    animCollapse: true,
                    closable: true,
                    collapsible: true,
                    glyph: '220@Sosa',
                    title: 'user\'s detail',
                    titleCollapse: true,
                    items: [
                        {
                            xtype: 'container',
                            html: '<p>Select a user in user\'s list</p>'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});