/*
 * File: app/view/UsersPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sxapim.view.UsersPanel', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar'
    ],

    itemId: 'usersPanel',
    layout: {
        type: 'border'
    },
    closable: true,
    title: 'User\'s list',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 2,
                    region: 'center',
                    id: '',
                    itemId: 'UsersGridPanel',
                    store: 'UsersStore',
                    viewConfig: {
                        itemId: 'UserGridView'
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            defaultWidth: 50,
                            dataIndex: 'id',
                            text: 'Id'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'firstname',
                            text: 'Firstname'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'lastname',
                            text: 'Lastname',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'mail',
                            text: 'Mail'
                        },
                        {
                            xtype: 'gridcolumn',
                            defaultWidth: 50,
                            dataIndex: 'pin',
                            text: 'Pin'
                        },
                        {
                            xtype: 'actioncolumn',
                            itemId: 'usergridactioncolumn',
                            defaultWidth: 20,
                            dataIndex: 'pin',
                            emptyCellText: 'Action',
                            menuText: 'Action',
                            altText: 'Action',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        console.log(record);
                                    },
                                    altText: 'Open',
                                    icon: 'resources/images/test.gif',
                                    tooltip: 'Open in new tab'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'east',
                    itemId: 'UsersAdditionalPanel',
                    layout: {
                        type: 'accordion'
                    },
                    collapsible: true,
                    title: 'Additionals',
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Detail'
                        },
                        {
                            xtype: 'panel',
                            title: 'Graphics',
                            dockedItems: [
                                {
                                    xtype: 'chart',
                                    dock: 'left',
                                    width: 200,
                                    shadow: false,
                                    autoSize: true,
                                    animate: true,
                                    insetPadding: 0,
                                    store: 'UsersStore',
                                    theme: 'Red',
                                    axes: [
                                        {
                                            type: 'Category',
                                            fields: [
                                                'firstname'
                                            ],
                                            position: 'left'
                                        },
                                        {
                                            type: 'Numeric',
                                            fields: [
                                                'visitcounter'
                                            ],
                                            position: 'top',
                                            title: 'Visit',
                                            decimals: 0,
                                            minimum: 0
                                        }
                                    ],
                                    series: [
                                        {
                                            type: 'bar',
                                            label: {
                                                display: 'insideEnd',
                                                field: 'visitcounter',
                                                color: '#fff',
                                                'text-anchor': 'middle'
                                            },
                                            xField: 'firstname',
                                            yField: 'visitcounter',
                                            stacked: false
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});