/*
 * File: app/view/apis.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SxapiManager.view.apis', {
    extend: 'Ext.panel.Panel',

    id: 'apis',
    layout: {
        type: 'border'
    },
    closable: true,
    iconCls: 'icon-menu-api',
    title: 'API',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    store: 'apis',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-add',
                                    text: 'Add'
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-filter',
                                    text: 'Filter'
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-actions',
                                    text: 'Actions'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'apis'
                        }
                    ],
                    viewConfig: {

                    },
                    plugins: [
                        Ext.create('Ext.grid.plugin.RowEditing', {
                            ptype: 'rowediting',
                            clicksToMoveEditor: 1
                        })
                    ],
                    listeners: {
                        select: {
                            fn: me.onGridpanelSelect,
                            scope: me
                        }
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '_id',
                            text: '_id'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'name',
                            text: 'Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'version',
                            text: 'Version'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'owner',
                            text: 'Owner'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'desc',
                            text: 'Desc'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    height: 150,
                    id: 'apisDetail',
                    styleHtmlContent: true,
                    resizable: true,
                    resizeHandles: 'n',
                    bodyPadding: 10,
                    title: 'Detail'
                }
            ]
        });

        me.callParent(arguments);
    },

    onGridpanelSelect: function(selModel, record, index, options) {
        if (record) {
            var detailPanel = Ext.getCmp('apisDetail');
            var bookTplMarkup = [
            'Name: <a href="{name}" target="_blank">{name}</a><br/>',
            'Author: {owner}<br/>',
            'Version: {version}<br/>',
            'Description: {desc}<br/>'
            ];
            var bookTpl = Ext.create('Ext.Template', bookTplMarkup);
            bookTpl.overwrite(detailPanel.body, record.data);
        }
    }

});