/*
 * File: app/view/logs.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SxapiManager.view.logs', {
    extend: 'Ext.panel.Panel',

    id: 'logs',
    layout: {
        type: 'border'
    },
    closable: true,
    iconCls: 'icon-menu-logs',
    title: 'API Logs',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            id: 'addbtn',
                            iconCls: 'icon-add',
                            text: 'Add'
                        },
                        {
                            xtype: 'button',
                            id: 'delbtn',
                            iconCls: 'icon-delete',
                            text: 'Delete'
                        },
                        {
                            xtype: 'button',
                            id: 'filterbtn',
                            iconCls: 'icon-filter',
                            text: 'Filter'
                        },
                        {
                            xtype: 'button',
                            id: 'actionbtn',
                            iconCls: 'icon-actions',
                            text: 'Actions'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    id: 'logs_grid',
                    store: 'logs',
                    viewConfig: {

                    },
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'logs'
                        }
                    ],
                    plugins: [
                        Ext.create('Ext.grid.plugin.RowEditing', {
                            ptype: 'rowediting',
                            clicksToMoveEditor: 1
                        })
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '_id',
                            text: '_id'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'type',
                            text: 'Type'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'message',
                            flex: 1,
                            text: 'Message'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'session',
                            text: 'Session'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: 'Date'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'level',
                            text: 'Level'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'code',
                            text: 'Code'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ip',
                            text: 'Ip'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    height: 150,
                    id: 'logs_detail',
                    styleHtmlContent: true,
                    resizable: true,
                    resizeHandles: 'n',
                    bodyPadding: 10,
                    title: 'Detail'
                }
            ]
        });

        me.callParent(arguments);
    }

});