/*
 * File: app/view/main.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SxapiManager.view.main', {
    extend: 'Ext.container.Viewport',

    id: 'main',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    region: 'north',
                    height: 45,
                    id: 'mainHeader',
                    layout: {
                        type: 'column'
                    },
                    items: [
                        {
                            xtype: 'container',
                            columnWidth: 0.8,
                            html: '<h1 style="margin: 0; font-weight: bold">SXAPI-Manager</h1>',
                            id: 'mainheader_title',
                            styleHtmlContent: true
                        },
                        {
                            xtype: 'container',
                            columnWidth: 0.2,
                            id: 'mainheader_options',
                            autoScroll: false,
                            layout: {
                                align: 'middle',
                                pack: 'center',
                                padding: 10,
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    width: 120,
                                    text: 'Options',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                handler: function(item, event) {
                                                    // instanciate view if not already done
                                                    var tabID = "session";
                                                    var tabExist = Ext.getCmp('maincontent').items.find(function(i){
                                                        return i.id === tabID;
                                                    });
                                                    if (!tabExist) { 
                                                        var view = Ext.create('SxapiManager.view.session');
                                                        Ext.getCmp('maincontent').add(view).show();
                                                    } else {
                                                        Ext.getCmp('maincontent').setActiveTab(tabID);
                                                    }
                                                },
                                                iconCls: 'icon-menu-session',
                                                text: 'Current session',
                                                tooltip: 'Your user profile',
                                                tooltipType: 'title'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    margin: '0 0 0 10px',
                                    text: 'Disconnect'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    region: 'center',
                    id: 'mainBoard',
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'menu',
                            collapseMode: 'header',
                            region: 'west',
                            floating: false,
                            width: 200,
                            resizable: true,
                            resizeHandles: 'e',
                            collapsible: true,
                            title: 'Main menu',
                            titleAlign: 'center',
                            titleCollapse: true,
                            items: [
                                {
                                    xtype: 'menuitem',
                                    handler: function(item, event) {
                                        // instanciate store if not already done
                                        if(Ext.getStore('apis') === undefined)
                                        Ext.create('SxapiManager.store.apis');
                                        // instanciate view if not already done
                                        var tabID = "apis";
                                        var tabExist = Ext.getCmp('maincontent').items.find(function(i){
                                            return i.id === tabID;
                                        });
                                        if (!tabExist) { 
                                            var view = Ext.create('SxapiManager.view.apis');
                                            Ext.getCmp('maincontent').add(view).show();
                                        } else {
                                            Ext.getCmp('maincontent').setActiveTab(tabID);
                                        }
                                    },
                                    iconCls: 'icon-menu-api',
                                    text: 'API Manager',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                handler: function(item, event) {
                                                    // instanciate store if not already done
                                                    if(Ext.getStore('apis') === undefined)
                                                    Ext.create('SxapiManager.store.apis');
                                                    // instanciate view if not already done
                                                    var tabID = "apis";
                                                    var tabExist = Ext.getCmp('maincontent').items.find(function(i){
                                                        return i.id === tabID;
                                                    });
                                                    if (!tabExist) { 
                                                        var view = Ext.create('SxapiManager.view.apis');
                                                        Ext.getCmp('maincontent').add(view).show();
                                                    } else {
                                                        Ext.getCmp('maincontent').setActiveTab(tabID);
                                                    }
                                                },
                                                iconCls: 'icon-menu-api',
                                                text: 'Api'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                iconCls: 'icon-menu-application',
                                                text: 'Applications'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                iconCls: 'icon-menu-model',
                                                text: 'Models'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                iconCls: 'icon-menu-ressource',
                                                text: 'Ressources'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                iconCls: 'icon-menu-session',
                                                text: 'Sessions'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                iconCls: 'icon-menu-user',
                                                text: 'Users'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                handler: function(item, event) {
                                                    // instanciate store if not already done
                                                    if(Ext.getStore('logs') === undefined)
                                                    Ext.create('SxapiManager.store.logs');
                                                    // instanciate view if not already done
                                                    var tabID = "logs";
                                                    var tabExist = Ext.getCmp('maincontent').items.find(function(i){
                                                        return i.id === tabID;
                                                    });
                                                    if (!tabExist) { 
                                                        var view = Ext.create('SxapiManager.view.logs');
                                                        Ext.getCmp('maincontent').add(view).show();
                                                    } else {
                                                        Ext.getCmp('maincontent').setActiveTab(tabID);
                                                    }
                                                },
                                                iconCls: 'icon-menu-logs',
                                                text: 'Logs'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'menuitem',
                                    iconCls: 'icon-menu-opportunity',
                                    text: 'Opportunities'
                                }
                            ]
                        },
                        {
                            xtype: 'tabpanel',
                            region: 'center',
                            id: 'maincontent',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    html: '<p>Welcome on SXAPI Manager version 0.1</p>',
                                    styleHtmlContent: true,
                                    bodyPadding: '10px',
                                    closable: true,
                                    iconCls: 'icon-menu-home',
                                    title: 'Welcome'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});