/*
 * File: app/view/session.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SxapiManager.view.session', {
    extend: 'Ext.panel.Panel',

    id: 'session',
    styleHtmlContent: true,
    resizable: true,
    resizeHandles: 'n',
    layout: {
        type: 'accordion'
    },
    closable: true,
    closeAction: 'hide',
    iconCls: 'icon-menu-user',
    title: 'My session',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    fieldDefaults: {
                        labelAlign: 'right',
                        labelWidth: 200,
                        anchor: '100%'
                    },
                    frame: true,
                    id: 'session_detail',
                    bodyPadding: 10,
                    collapsed: false,
                    iconCls: 'icon-menu-session',
                    title: 'Session detail',
                    items: [
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            name: 'api',
                            fieldLabel: 'Connected API'
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            name: 'state',
                            fieldLabel: 'State'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    html: 'yyyy',
                    id: 'session_user',
                    collapsed: true,
                    iconCls: 'icon-menu-user',
                    title: 'Associated user'
                },
                {
                    xtype: 'panel',
                    html: 'zzzz',
                    id: 'session_application',
                    collapsed: true,
                    iconCls: 'icon-menu-application',
                    title: 'Associated application'
                }
            ]
        });

        me.callParent(arguments);
    }

});