/*
 * File: app/view/credentials.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SxapiManager.view.credentials', {
    extend: 'Ext.window.Window',

    height: 140,
    id: 'credentials',
    width: 350,
    layout: {
        type: 'fit'
    },
    closable: false,
    title: 'Authentification',
    maximizable: false,
    maximized: false,
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    url: 'http://127.0.0.1/git/startx_api/session/auth?format=json',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'login',
                            fieldLabel: 'Login',
                            labelAlign: 'right',
                            allowBlank: false,
                            vtype: 'alphanum'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            inputType: 'password',
                            name: 'pwd',
                            fieldLabel: 'Password',
                            labelAlign: 'right',
                            allowBlank: false,
                            vtype: 'alphanum'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var logform = this.up('form').getForm();
                                        loginwindow = this.up('window');
                                        if (logform.isValid()) {
                                            logform.submit({
                                                success: function(form, action) {
                                                    Ext.getCmp('loadingmessagebox').update('... '+action.result.message+' ...');
                                                    var values = form.getValues();
                                                    var credentialstore = Ext.getStore('credential');
                                                    credentialstore.add(form.getValues());
                                                    credentialstore.save();
                                                    var storedInfo = credentialstore.first();
                                                    loginwindow.hide();
                                                    SxapiManager.getApplication().launchMain();
                                                },
                                                failure: function(form, action) {
                                                    var response = JSON.parse(action.response.responseText);
                                                    Ext.getCmp('loadingmessagebox').update('... authentication failed ...');
                                                    Ext.Msg.alert('Authentication error', response.success ? response.message : 'Error in server response');
                                                }
                                            });
                                        }
                                        else {
                                            Ext.Msg.alert('Wrong input', 'You have to fill all required fields');
                                        }
                                    },
                                    text: 'Connection'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});