/*
 * File: app/view/loading.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SxapiManager.view.loading', {
    extend: 'Ext.window.Window',

    autoRender: false,
    height: 202,
    hidden: false,
    id: 'loading',
    width: 334,
    closable: false,
    expandOnShow: false,
    modal: true,
    plain: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'image',
                    dock: 'top',
                    id: 'loadingAppImg',
                    itemId: 'loadingAppImg',
                    margin: 10,
                    src: 'assets/images/startx.png'
                },
                {
                    xtype: 'container',
                    dock: 'top',
                    height: 60,
                    html: '<h1> SXAPI Manager 1.0</h1>',
                    margin: '0 0 0 50px',
                    styleHtmlContent: true,
                    width: 249
                }
            ],
            items: [
                {
                    xtype: 'container',
                    html: 'start loading...',
                    id: 'loadingmessagebox',
                    itemId: 'loadingmessagebox',
                    margin: 10,
                    styleHtmlContent: true
                }
            ]
        });

        me.callParent(arguments);
    }

});