/*
 * File: app/store/api.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SxapiManager.store.api', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            storeId: 'api',
            proxy: {
                type: 'ajax',
                url: 'http://127.0.0.1/git/startx_api/api?format=json',
                reader: {
                    type: 'json',
                    idProperty: '_id',
                    root: 'data'
                }
            },
            fields: [
                {
                    name: 'desc'
                },
                {
                    name: '_id'
                },
                {
                    name: 'version'
                }
            ]
        }, cfg)]);
    }
});