/*
 * File: app/controller/Session.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SxapiManager.controller.Session', {
    extend: 'Ext.app.Controller',

    models: [
        'Credential',
        'SessionUser'
    ],
    stores: [
        'session',
        'sessionApplication',
        'credential',
        'sessionUser',
        'sessionData',
        'api',
        'apis'
    ],
    views: [
        'session',
        'credentials',
        'apis'
    ],

    refs: [
        {
            ref: 'viewDetail',
            selector: '#session_detail'
        },
        {
            ref: 'view',
            selector: '#session'
        }
    ],

    onSessionAfterRender: function(abstractcomponent, options) {
        var data = this.getSessionStore().first();
        var form = Ext.getCmp('session_detail').getForm();
        form.loadRecord(data);
    },

    onLaunch: function() {

        console.log("launch controller session");
    },

    init: function(application) {
        this.control({
            "#session": {
                afterrender: this.onSessionAfterRender
            }
        });
    }

});
