/*
 * File: app/view/logs/Filters.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SxapiManager.view.logs.Filters', {
    extend: 'Ext.window.Window',

    height: 250,
    id: 'logs_filter',
    width: 400,
    title: 'Filter',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});