/*
 * File: app/controller/Navigation.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sxapim.controller.Navigation', {
    extend: 'Ext.app.Controller',

    views: [
        'HomePanel'
    ],

    refs: [
        {
            ref: 'mainPanel',
            selector: '#mainPanel'
        },
        {
            ref: 'mainMenu',
            selector: '#mainMenu'
        }
    ],

    onMenuitemClick: function(item, e, eOpts) {
        location.hash = item.itemId;
        this.navigate(item.itemId);
    },

    onLaunch: function() {

        /**
        * The following code implements simple navigation by
        * using the URL hash (#) to indicate the active view
        *
        * The following values are always equal
        * hash = active menu 'itemId' = active panel 'itemId' + 'Panel'
        */

        // Use var for controller
        var ctrl = this;

        this.navigate('home');

        // Init the Ext history utility
        //Ext.History.init();

        // Navigate on hash change
        //Ext.History.on('change', function(hash) {
        //    ctrl.navigate(hash);
        //});

        // Navigate if initial hash is provided
        var hash = window.location.hash;
        if (hash) {
            ctrl.navigate(hash);
        }

    },

    navigate: function(id) {
        // Use var for controller
        var ctrl = this;

        // Remove # from id if present
        if (id[0] == '#') id = id.slice(1);

        // set variables
        var panelId = id + 'Panel',
            tabFound = false,
            menu = this.getMainMenu(),
            main = this.getMainPanel();

        // add and activate tab panel
        if(main && main.layout) {
            // Search for existing tab
            Ext.each(main.layout.getLayoutItems(), function(panel, index) {
                if(panel.getItemId() == panelId) {
                    tabFound = true;
                }
            });

            // add new tab if doesn't already exist
            if(!tabFound) {
                var classname = panelId.charAt(0).toUpperCase() + panelId.slice(1);
                var newpanelclass = 'sxapim.view.'+classname;
                var newpanel = Ext.create({
                 xclass: newpanelclass
                });
                main.add(newpanel);
            }
            // select appropriate tab
            main.layout.setActiveItem(panelId);
        }

        // Set menu and page title
        if(menu && menu.items) {
            menu.items.each(function(item) {
                // Active
                if (item.href == '#' + id) {
                    // Disable
                    item.disable();
                    // Set page title to menu item text
                    window.document.title = item.text;
                }

                // Inactive
                else {
                    item.enable();
                }
            });
        }

    },

    init: function(application) {
        this.control({
            "menuitem": {
                click: this.onMenuitemClick
            }
        });
    }

});
