/*
 * File: app/view/logs/Actions.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SxapiManager.view.logs.Actions', {
    extend: 'Ext.window.Window',

    height: 300,
    id: 'logs_actions',
    minHeight: 200,
    styleHtmlContent: false,
    width: 550,
    layout: {
        animate: true,
        type: 'accordion'
    },
    title: 'Actions',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    overflowY: 'auto',
                    bodyPadding: 5,
                    collapsed: false,
                    title: 'Change property',
                    items: [
                        {
                            xtype: 'fieldset',
                            collapsible: true,
                            title: 'Message',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    name: 'message',
                                    fieldLabel: 'New message'
                                },
                                {
                                    xtype: 'button',
                                    align: 'right',
                                    style: 'float:right',
                                    text: 'Apply change'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            collapsed: true,
                            collapsible: true,
                            title: 'Date',
                            items: [
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    name: 'date',
                                    fieldLabel: 'New date'
                                },
                                {
                                    xtype: 'button',
                                    align: 'right',
                                    style: 'float:right',
                                    text: 'Apply change'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            collapsed: true,
                            collapsible: true,
                            title: 'Type',
                            items: [
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    name: 'type',
                                    fieldLabel: 'New date'
                                },
                                {
                                    xtype: 'button',
                                    align: 'right',
                                    style: 'float:right',
                                    text: 'Apply change'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            collapsed: true,
                            collapsible: true,
                            title: 'Level',
                            items: [
                                {
                                    xtype: 'slider',
                                    anchor: '100%',
                                    name: 'level',
                                    value: 5,
                                    fieldLabel: 'New date',
                                    maxValue: 10
                                },
                                {
                                    xtype: 'button',
                                    align: 'right',
                                    style: 'float:right',
                                    text: 'Apply change'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            collapsed: true,
                            collapsible: true,
                            title: 'Code',
                            items: [
                                {
                                    xtype: 'slider',
                                    anchor: '100%',
                                    name: 'code',
                                    value: 500,
                                    fieldLabel: 'New date',
                                    maxValue: 1000
                                },
                                {
                                    xtype: 'button',
                                    align: 'right',
                                    style: 'float:right',
                                    text: 'Apply change'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            collapsed: true,
                            collapsible: true,
                            title: 'IP',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    name: 'ip',
                                    fieldLabel: 'New date'
                                },
                                {
                                    xtype: 'button',
                                    align: 'right',
                                    style: 'float:right',
                                    text: 'Apply change'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    collapsed: true,
                    title: 'Export',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'button',
                                    align: 'right',
                                    style: 'float:right',
                                    text: 'Apply change'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});